"""
Pydantic v2 models for weekly challenges and monthly insights.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# ──────────────────────────────────────────────────────
# Challenges
# ──────────────────────────────────────────────────────


class ChallengeCreate(BaseModel):
    """Request body for creating a weekly challenge.

    Attributes:
        title: Short title for the challenge.
        description: Longer description with instructions.
        category: Emission category the challenge targets.
        targetMetric: Quantitative goal description.
        co2SavingKg: Estimated CO₂ saving if the challenge is met.
    """

    title: str = Field(
        ...,
        min_length=3,
        max_length=120,
        description="Challenge title",
        json_schema_extra={"examples": ["Meatless Monday Week"]},
    )
    description: str = Field(
        ...,
        min_length=10,
        max_length=500,
        description="Challenge instructions",
        json_schema_extra={
            "examples": [
                "Skip all meat meals on Monday for the whole week."
            ]
        },
    )
    category: str = Field(
        ...,
        description="Emission category (transport, food, energy, shopping)",
        json_schema_extra={"examples": ["food"]},
    )
    targetMetric: str = Field(
        ...,
        description="Quantitative goal description",
        json_schema_extra={"examples": ["0 meat meals on Mondays"]},
    )
    co2SavingKg: float = Field(
        ...,
        ge=0,
        description="Estimated weekly CO₂ saving in kg",
        json_schema_extra={"examples": [4.5]},
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "title": "Meatless Monday Week",
                    "description": "Skip all meat meals on Monday for the whole week.",
                    "category": "food",
                    "targetMetric": "0 meat meals on Mondays",
                    "co2SavingKg": 4.5,
                }
            ]
        }
    }


class ChallengeResponse(BaseModel):
    """Response shape for a weekly challenge.

    Attributes:
        id: Firestore document ID (``YYYY-WW`` format).
        title: Challenge title.
        description: Challenge instructions.
        category: Emission category.
        targetMetric: Goal description.
        co2SavingKg: Estimated saving.
        status: ``active`` | ``completed`` | ``failed``.
    """

    id: str = Field(..., description="Challenge ID (YYYY-WW)")
    title: str
    description: str
    category: str
    targetMetric: str
    co2SavingKg: float
    status: str = Field(
        default="active",
        description="Challenge status",
        json_schema_extra={"examples": ["active"]},
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "id": "2026-W24",
                    "title": "Meatless Monday Week",
                    "description": "Skip all meat meals on Monday for the whole week.",
                    "category": "food",
                    "targetMetric": "0 meat meals on Mondays",
                    "co2SavingKg": 4.5,
                    "status": "active",
                }
            ]
        }
    }


class ChallengeStatusUpdate(BaseModel):
    """Request body for updating a challenge's status.

    Attributes:
        status: New status value.
    """

    status: str = Field(
        ...,
        description="New status (active | completed | failed)",
        json_schema_extra={"examples": ["completed"]},
    )

    model_config = {
        "json_schema_extra": {
            "examples": [{"status": "completed"}]
        }
    }


# ──────────────────────────────────────────────────────
# Insights
# ──────────────────────────────────────────────────────


class InsightResponse(BaseModel):
    """Monthly insight summary generated by Gemini.

    Attributes:
        month: ``YYYY-MM`` identifier.
        totalCo2Kg: Total CO₂ for the month.
        prevMonthCo2Kg: Previous month's total for comparison.
        narrative: AI-generated narrative insight.
        generatedAt: ISO-8601 timestamp.
    """

    month: str = Field(
        ...,
        description="Month identifier (YYYY-MM)",
        json_schema_extra={"examples": ["2026-06"]},
    )
    totalCo2Kg: float = Field(
        default=0.0,
        description="Total CO₂ for the month in kg",
        json_schema_extra={"examples": [142.5]},
    )
    prevMonthCo2Kg: Optional[float] = Field(
        default=None,
        description="Previous month's CO₂ for comparison",
        json_schema_extra={"examples": [158.0]},
    )
    narrative: str = Field(
        default="",
        description="AI-generated narrative insight",
        json_schema_extra={
            "examples": [
                "Great progress! You cut your footprint by 10% this month."
            ]
        },
    )
    generatedAt: Optional[str] = Field(
        default=None,
        description="ISO-8601 generation timestamp",
        json_schema_extra={"examples": ["2026-06-08T12:00:00Z"]},
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "month": "2026-06",
                    "totalCo2Kg": 142.5,
                    "prevMonthCo2Kg": 158.0,
                    "narrative": "Great progress! You cut your footprint by 10% this month.",
                    "generatedAt": "2026-06-08T12:00:00Z",
                }
            ]
        }
    }
